name: AutoTransform

on:
  push:
    branches: [ master ]

jobs:
  sync-upstream:
    runs-on: ubuntu-latest

    steps:
      # 检出代码库
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置 Python 环境
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/AutoTransform/requirements.txt
          
      # 运行 Python 脚本并传递 Secrets
      - name: Run Python script
        env:
          API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: python .github/workflows/AutoTransform/auto_transform.py

      # 安装 Git
      - name: Setup Git
        run: sudo apt-get install git
        
      # 设置 Git 用户信息
      - name: Set Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@mtools.ink"

      # 创建 Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: "Auto-generated commit for feature branch"
          branch: ${{ github.ref_name }}
          base: master
          title: "Auto PR: ${{ github.ref_name }}"
          body: |
            This pull request was automatically created by GitHub Actions.
